### ISSUE TITLE
U+202E 好像没有喔

### ISSUE THREAD

**Issue by ubnm** [330k/misc_tools#1]
大佬，可以增加U+202E的选项吗，解不出这里的
https://github.com/RobinLinus/wutf/blob/master/index.html

**Comment by 330k** [comment]
U+202Eは文の方向を変えるためにステガノグラフィが埋め込まれた文章が壊れます。

もしくは、自分でunicodeSteganographer.setUseChars(String)を使うようにすることでU+202Eを使うことができます。
